[dependencies]
base = "0.14.14"
new-base = "0.4.0"
map = "9.0.1"
http-parser = "0.3.4"
base-x-encoder = "1.2.0"
server = "2.0.0"
jwt = "1.1.0"
json = "1.3.0"
ecdsa = "6.0.0"
xtended-numbers = "0.4.0"
sha2 = "0.1.4"
icrc2-types = "1.1.0"

[toolchain]
moc = "0.14.14"
