packages:
  - packages/canisters/*
  - packages/apps/*
  - packages/services/*
  - packages/libs/*
  - packages/tests/*

onlyBuiltDependencies:
  - '@dfinity/pic'
  - '@tailwindcss/oxide'
  - esbuild
