name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  # =================================================================
  # Job 1: Run fast Motoko unit tests first
  # =================================================================
  unit-tests:
    name: Motoko Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 2. Setup Mops
        uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: 3. Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 4. Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 5. Setup DFX # <<< ADDED
        uses: dfinity/setup-dfx@main

      - name: 6. Install Dependencies
        run: pnpm install

      - name: 7. Install Mops Dependencies
        run: mops install

      - name: 8. Run Motoko Tests
        run: pnpm test:mo
        # This uses our package.json script to run `mops test` in all canister packages

  picjs-tests:
    name: PicJS Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 2. Setup Mops
        uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: 3. Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 4. Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 5. Setup DFX
        uses: dfinity/setup-dfx@main

      - name: 6. Install Dependencies
        run: pnpm install

      - name: 7. Install Mops Dependencies
        run: mops install

      - name: 8. Build Canister Declarations
        run: dfx generate mcp_registry && dfx generate auth_server && dfx generate icrc1_ledger

      - name: 9. Run PicJS Tests
        run: pnpm test:canisters

  # =================================================================
  # Job 2: Run slower E2E tests only if unit tests pass
  # =================================================================
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [unit-tests, picjs-tests]

    steps:
      - name: 1. Check out repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 2. Setup Mops
        uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: 3. Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 4. Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 5. Setup DFX
        uses: dfinity/setup-dfx@main

      - name: 6. Install Dependencies
        run: pnpm install

      - name: 7. Install Mops Dependencies
        run: mops install

      - name: 8. Start Local Replica
        run: dfx start --background --clean

      - name: 9. Deploy All Canisters
        run: dfx deploy

      - name: 10. Run E2E Tests
        run: pnpm test

      - name: 11. Stop Local Replica
        if: always() # Ensure this runs even if tests fail
        run: dfx stop

  # =================================================================
  # Job 3: Aggregate status for a single required check
  # =================================================================
  ci-status-check:
    name: CI Status Check
    if: always()
    needs: [unit-tests, picjs-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs
        if: ${{ needs.unit-tests.result != 'success' || needs.picjs-tests.result != 'success' || needs.e2e-tests.result != 'success' }}
        run: exit 1
